### ISSUE TITLE
Task :app:checkDebugDuplicateClasses FAILED

### ISSUE THREAD

**Issue by sagarj-iprogrammer** [juspay/hyper-sdk-react#21]
"hyper-sdk-react": "^3.0.8",

after uninstalling and installing same package app runs new arch 0.72.2

A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable > Duplicate class com.amazon.apay.hardened.activity.APayBrowserActivity found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.activity.APayBrowserActivity$a found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.activity.RedirectUriReceiverActivity found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.AmazonPayManager found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.AmazonPayManager$a found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.AmazonPayManager$b found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.model.APayAuthResponse found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.model.APayAuthResponse$Status found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.model.APayCallback found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.model.APayConstants found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.model.APayConstants$Error found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.model.APayError found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.model.APayError$ErrorType found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.apay.hardened.external.model.APayRequestContext found in modules jetified-amazonpay-hardened-silentpay-sdk-1.3.0-runtime (in.juspay:amazonpay-hardened-silentpay-sdk:1.3.0) and jetified-apay-hardened-android-sdk-sso-1.1.1-runtime (com.amazon.android.amazonpay:apay-hardened-android-sdk-sso:1.1.1) Duplicate class com.amazon.identity.auth.device.AuthError found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.AuthError$ERROR_CATEGORY found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.AuthError$ERROR_TYPE found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.CancellableListener found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.Listener found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.SDKInfo found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.AuthCancellation found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.AuthCancellation$Cause found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.AuthorizationManager found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.AuthorizeListener found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.AuthorizeRequest found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.AuthorizeRequest$Builder found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.AuthorizeRequest$GrantType found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.AuthorizeResult found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.ProfileScope found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.Region found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.Scope found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.ScopeFactory found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.ScopeFactory$a found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.authorization.User found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.api.workflow.RequestContext found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.interactive.InteractiveAPI found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.interactive.InteractiveListener found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.interactive.InteractiveRequest found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.interactive.InteractiveRequest$Builder found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.interactive.InteractiveRequestRecord found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.shared.APIListener found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.device.workflow.WorkflowActivity found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.internal.BrowsingExperienceManager found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.internal.BrowsingExperienceManager$a found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.internal.BrowsingExperienceManager$b found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Duplicate class com.amazon.identity.auth.internal.BrowsingExperienceManager$c found in modules jetified-amazonpay-silentpay-sdk-1.2.0-runtime (in.juspay:amazonpay-silentpay-sdk:1.2.0) and jetified-apay-identity-mobile-android-sdk-sso-2.0.1-runtime (com.amazon.android.amazonpay:apay-identity-mobile-android-sdk-sso:2.0.1) Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>. * Try:

**Comment by Subhash703** [comment]
Please check with latest hyper-sdk-react version and reach out to Juspay support team if you are still facing issue.
