### ISSUE TITLE
Not compatible with react-native 0.73.0

### ISSUE THREAD

**Issue by MiteshKalal7** [juspay/hyper-sdk-react#32]

**Comment by kailash-sssg** [comment]
I am facing the issue with installing with pod-install while running on 0.73 with this SDK. It's failing

**Comment by Subhash703** [comment]
@kailash-sssg  @MiteshKalal7  Could you please share more information on what error you are getting?

**Comment by Subhash703** [comment]
Closing this as the latest version works with react-native version 0.73+ 
Please reopen in case you are still facing the issue
