### ISSUE TITLE
React native APK Build Issue

### ISSUE THREAD

**Issue by Arjit0762** [juspay/hyper-sdk-react#39]
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve in.juspay.merchants:hyper.assets.****:1.0.0.
     Required by:
         project :app > project :hyper-sdk-react
      > Could not resolve in.juspay.merchants:hyper.assets.****:1.0.0.
         > Could not get resource 'https://maven.juspay.in/jp-build-packages/hyper-sdk/in/juspay/merchants/hyper.assets.****/1.0.0/hyper.assets.****-1.0.0.pom'.
            > Could not GET 'https://maven.juspay.in/jp-build-packages/hyper-sdk/in/juspay/merchants/hyper.assets.****/1.0.0/hyper.assets.****-1.0.0.pom'. Received status code 403 from server: Forbidden

Showing this error while building apk

**Comment by harshgarg18** [comment]
Set clientId ext property in your root build.gradle file to the one assigned to you by Juspay Support team.

**Comment by piyushchhabra1122** [comment]
Facing the same issue after adding clientId
