### ISSUE TITLE
Issue on doing gradle build for RN 0.73 version

### ISSUE THREAD

**Issue by Yashh221** [juspay/hyper-sdk-react#63]
i am getting error as 
A problem occurred evaluating project ':hyper-sdk-react'.
> Could not set unknown property 'excludedMicroSDKs' for extension 'hyperSdkPlugin' of type java.lang.Object.

followed all the step mention in readme file as well as intialization step on juspay docs. What can be the possible issue? please help it out

**Comment by Subhash703** [comment]
Closing this issue because of it has been inactive.
