### ISSUE TITLE
Provide Expo support for hyper-sdk-react

### ISSUE THREAD

**Issue by Kuljeet-123** [juspay/hyper-sdk-react#66]
- Since we are using `Expo` for our project, whenever we write or change some code and run the `prebuild` with the `--clean` command for different environments, it deletes the native code we have written. Provide a config plugin so that we don't need to modify the native code repeatedly after each `prebuild`.
-  We also have different environments like `staging` and `production`, for which we have to rewrite the target in the `Podfile` whenever we change environments and run `prebuild`. Please address this issue as well.

**Comment by Subhash703** [comment]
Hi @Kuljeet-123 ,

We will check and explore expo config plugin to automate the native code changes.

**Comment by AamirHafiez** [comment]
Any update on this?

**Comment by pratyush0103** [comment]
@Subhash703 any update on this?

**Comment by punndcoder28** [comment]
Hi @Subhash703 has there been any update on this? We are also facing similar issues where in we have to write the native code all over again once prebuild command is run?

**Comment by Subhash703** [comment]
Hi @Kuljeet-123 @AamirHafiez  @pratyush0103  @punndcoder28  - We have published an expo config plugin to automate required native changes for `hyper-sdk-react`. Please check [hyper-sdk-expo-plugin](www.npmjs.com/package/hyper-sdk-expo-plugin). 

@Kuljeet-123  Regarding your 2nd issue, hyper-sdk-react doesn't need any target specific change change in Podfile so don't think there is anything to be done from our end. Please share more details if possible.

Please reach out to us in case you face any issue.

**Comment by AamirHafiez** [comment]
> Hi @Kuljeet-123 @AamirHafiez @pratyush0103 @punndcoder28 - We have published an expo config plugin to automate required native changes for `hyper-sdk-react`. Please check [hyper-sdk-expo-plugin](www.npmjs.com/package/hyper-sdk-expo-plugin).
> 
> @Kuljeet-123 Regarding your 2nd issue, hyper-sdk-react doesn't need any target specific change change in Podfile so don't think there is anything to be done from our end. Please share more details if possible.
> 
> Please reach out to us in case you face any issue.

@Subhash703 [hyper-sdk-expo-plugin](https://github.com/juspay/hyper-sdk-react/issues/www.npmjs.com/package/hyper-sdk-expo-plugin), This link gives a 404. Can you please check if the changes were published.

Thanks.
