### ISSUE TITLE
Back CTA Not Visible in React Hyper SDK Integrated with React Native Expo Project

### ISSUE THREAD

**Issue by yuvrajchaudhari03** [juspay/hyper-sdk-react#68]
**Description:**

We have integrated the Juspay React Hyper SDK into our React Native Expo project. When the Juspay SDK is opened on the UI, the back CTA (call to action) is not showing. Although clicking on the top left corner navigates back and exits Juspay, there is no icon displayed for this action.

**Steps to Reproduce:**

Integrate the Juspay React Hyper SDK into a React Native Expo project.
Open the Juspay SDK within the app.
Observe the top left corner of the UI.
Expected Behavior:
The back CTA icon should be visible, allowing users to intuitively navigate back or exit Juspay.

**Actual Behavior:**
The back CTA icon is not displayed. Users can click on the top left corner to navigate back, but no icon is shown, leading to potential user confusion.

**Additional Information:**

"react-native": "0.74.2",
"expo": "~51.0.11",
"hyper-sdk-react": "^3.0.14",

**Attachments:**

![Simulator Screen Shot - iPhone 13 - 2024-07-25 at 16 13 56](https://github.com/user-attachments/assets/c2b6e0d0-6c98-474a-9f04-c80167fb36b9)

**Comment by Subhash703** [comment]
Hi @yuvrajchaudhari03 
This is not issue with the plugin. Please reach out to Juspay support team at support@juspay.in to get it fixed.
